/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ControleCaixa;
import Controle.ControlePedido;
import Controle.Controleitem;
import Modelo.Caixa;
import Modelo.ItemEntrega;
//import Modelo.Cliente;
import Modelo.Pedido;
import Modelo.Produto;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author APARECIDO MARCOS
 */
public class Entregas extends javax.swing.JDialog {

    private ControlePedido controledao = new ControlePedido();
    private List<Pedido> tabelalista = new ArrayList<>();

    private Controleitem contItem = new Controleitem();
//    private List<ItemEntrega> tabelaItem = new ArrayList<>();

    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");

    //  private List<Cliente> tabelaCliente = new ArrayList<>();
    /**
     * Creates new form Entregas
     */
    public Entregas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        atualizaTabela(true);

    }

    public void atualizaTabela(boolean flag) {
        DefaultTableModel modelo = (DefaultTableModel) TabelaEntrega.getModel();

        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }

        if (flag) {

            tabelalista.clear();
            tabelalista.addAll(controledao.listarTodos());

        }

        for (Pedido e : tabelalista) {

            modelo.addRow(new Object[]{e.getId(), formato.format(e.getDataentrega()), e.getLocal(), e.getCliente().getNome(),
                 });
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Novo = new javax.swing.JButton();
        alterar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        visualizar = new javax.swing.JButton();
        fechar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaEntrega = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        Novo.setBackground(new java.awt.Color(0, 0, 0));
        Novo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Novo.setForeground(new java.awt.Color(0, 204, 255));
        Novo.setText("NOVO");
        Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoActionPerformed(evt);
            }
        });
        jPanel1.add(Novo);

        alterar.setBackground(new java.awt.Color(0, 0, 0));
        alterar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        alterar.setForeground(new java.awt.Color(0, 204, 255));
        alterar.setText("ALTERAR");
        alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarActionPerformed(evt);
            }
        });
        jPanel1.add(alterar);

        excluir.setBackground(new java.awt.Color(0, 0, 0));
        excluir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        excluir.setForeground(new java.awt.Color(0, 204, 255));
        excluir.setText("EXCLUIR");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });
        jPanel1.add(excluir);

        visualizar.setBackground(new java.awt.Color(0, 0, 0));
        visualizar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        visualizar.setForeground(new java.awt.Color(0, 204, 255));
        visualizar.setText("VISUALIZAR");
        visualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarActionPerformed(evt);
            }
        });
        jPanel1.add(visualizar);

        fechar.setBackground(new java.awt.Color(204, 51, 0));
        fechar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fechar.setText("FECHAR");
        fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharActionPerformed(evt);
            }
        });
        jPanel1.add(fechar);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(150, 64));

        TabelaEntrega.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "DATA", "LOCAL", "CLIENTE", "PEDIDO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelaEntrega);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("AGENDA DE ENTREGAS");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/entregador (1).png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharActionPerformed
        // TODO add your handling code here
        dispose();
    }//GEN-LAST:event_fecharActionPerformed

    private void NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoActionPerformed
        // TODO add your handling code here:
        ControleCaixa caixa = new ControleCaixa();
        Caixa a = caixa.buscaCaixa(new Date());

        //Erro monstruoso 
//   if ( a.equals("a")){
//       
//             EntregaCliente tela = new EntregaCliente(null, true);
//        tela.setVisible(true);
//        if (tela.isSalvar()) {
//            
//            controledao.inserir(tela.getEntrega());
//            contItem.inserir(tela.getItemEntrega());
//            
//            atualizaTabela(true);
//        }
//            
//        }        
//        else{
//        JOptionPane.showInputDialog("Abra o Caixa para realizar um pedido!");
//        }
        EntregaCliente tela = new EntregaCliente(null, true);
        tela.NegaPagamento();
        tela.setVisible(true);
        if (tela.isSalvar()) {

            
                controledao.inserir(tela.getEntrega());
//           contItem.inserir(tela.getItemEntrega());
          

            atualizaTabela(true);
        } else {
            JOptionPane.showMessageDialog(null,"Abra o Caixa para realizar um pedido!");
        }


    }//GEN-LAST:event_NovoActionPerformed

    private void alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarActionPerformed
        // TODO add your handling code here:

        int nrItem = TabelaEntrega.getSelectedRow();
        if (nrItem == -1) {
            JOptionPane.showInputDialog(this, "Nenhuma Entrega foi selecionada");

        } else {

            EntregaCliente tela = new EntregaCliente(null, true);
            Pedido e = tabelalista.get(nrItem);
            
            tela.setEntrega(e);
            tela.verifica();
            tela.setVisible(true);
            if (tela.isSalvar()) {

          

                try {
                    controledao.alterar(tela.getEntrega());
                } catch (Exception ex) {
                    Logger.getLogger(Entregas.class.getName()).log(Level.SEVERE, null, ex);
                }
                atualizaTabela(true);
            }

        }

    }//GEN-LAST:event_alterarActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        // TODO add your handling code here:

        int linha = TabelaEntrega.getSelectedRow();

        if (linha == -1) {

            JOptionPane.showMessageDialog(this,
                    "Nenhuma Entrega foi selecionada");
        } else {

            controledao.excluir(tabelalista.get(linha));

            tabelalista.remove(linha);

            atualizaTabela(true);

        }

    }//GEN-LAST:event_excluirActionPerformed

    private void visualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarActionPerformed
        // TODO add your handling code here:
        int linha = 0;
        linha = TabelaEntrega.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Voce nao selecionou um Pedido");
        } else {
            Pedido p = new Pedido();
            // ItemEntrega i = new ItemEntrega();

//            i= tabelaItem.get(linha);
            p = tabelalista.get(linha);

            EntregaCliente tela = new EntregaCliente(null, true);

            tela.setEntrega(p);
            //tela.setItem(i);

            tela.desligarCampos();
            tela.setVisible(true);

        }
    }//GEN-LAST:event_visualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entregas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entregas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entregas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entregas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Entregas dialog = new Entregas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Novo;
    private javax.swing.JTable TabelaEntrega;
    private javax.swing.JButton alterar;
    private javax.swing.JButton excluir;
    private javax.swing.JButton fechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton visualizar;
    // End of variables declaration//GEN-END:variables
}
