/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ControleFornecedor;
import Controle.ControleProduto;
import Modelo.Fornecedor;
import java.text.SimpleDateFormat;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aluno
 */
public class TelaManutencaoFornecedor extends javax.swing.JDialog {

    private ControleFornecedor controledao = new ControleFornecedor();
    private List<Fornecedor> tabelalista = new ArrayList<>();

     SimpleDateFormat formato= new SimpleDateFormat("dd/MM/yyyy");
    
    //  public void isSalvar(Fornecedor f) {
    //  this.TXTnome.getText();
    // }
    /**
     * Creates new form TelaManutencaoFornecedor
     */
    public TelaManutencaoFornecedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        atualizaTabela(true);
    }

    public void atualizaTabela(boolean flag) {
        DefaultTableModel modelo = (DefaultTableModel) TabelaFornecedor.getModel();

        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }

        tabelalista.clear();
        tabelalista.addAll(controledao.listarTodos());

        for (Fornecedor f : tabelalista) {
            modelo.addRow(new Object[]{f.getCodigoFornecedor(), f.getNomeEmpresa(), f.getValorASerPago(), formato.format(f.getDataEntrega())});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        novo = new javax.swing.JButton();
        alterar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaFornecedor = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TXTpesquisar = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        novo.setBackground(new java.awt.Color(0, 0, 0));
        novo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        novo.setForeground(new java.awt.Color(0, 204, 255));
        novo.setText("NOVO");
        novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoActionPerformed(evt);
            }
        });
        jPanel1.add(novo);

        alterar.setBackground(new java.awt.Color(0, 0, 0));
        alterar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        alterar.setForeground(new java.awt.Color(0, 204, 255));
        alterar.setText("ALTERAR");
        alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarActionPerformed(evt);
            }
        });
        jPanel1.add(alterar);

        excluir.setBackground(new java.awt.Color(0, 0, 0));
        excluir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        excluir.setForeground(new java.awt.Color(0, 204, 255));
        excluir.setText("EXCLUIR");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });
        jPanel1.add(excluir);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 255));
        jButton1.setText("VISUALIZAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton3.setBackground(new java.awt.Color(204, 51, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("FECHAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(45, 64));

        TabelaFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CODIGO", "NOME", "VALOR A SER PAGO", "DATA DE ENTREGA"
            }
        ));
        jScrollPane1.setViewportView(TabelaFornecedor);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("FORNECEDORES");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fornecedor.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Pesquisar por Nome:");

        TXTpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTpesquisarActionPerformed(evt);
            }
        });

        jButton5.setText("PESQUISAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXTpesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TXTpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    public void limparCampo() {

        //  TXTcodigo.setText("");
        //   TXTnome.setText("");
        //   TXTvalor.setText("");
    }


    private void novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoActionPerformed
        // TODO add your handling code here:

        Cadastrofornecedor tela = new Cadastrofornecedor(null, true);
       tela.setVisible(true);
        if (tela.isSalvar()) {
            controledao.inserir(tela.getFornecedor());
            atualizaTabela(true);
        }

        /*
        Fornecedor f = new Fornecedor();
        
        f.setNomeEmpresa(TXTnome.getText());
        f.setCodigoFornecedor( Integer.valueOf(TXTcodigo.getText()));
        f.setValorASerPago( Float.valueOf( TXTvalor.getText()));
       f.setDataEntrega(Data.getDate());
        controledao.inserir(f);
        atualizaTabela(true);        
         */

    }//GEN-LAST:event_novoActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        // TODO add your handling code here:

        int linha = TabelaFornecedor.getSelectedRow();

        if (linha == -1) {

            JOptionPane.showMessageDialog(this,
                    "Nenhum Fornecedor foi selecionado");
        }
        
        //if(linha != -1){
      //  JOptionPane.showConfirmDialog(rootPane, linha);
       // }
        
        else {

            // excluir a sala do banco
            controledao.excluir(tabelalista.get(linha));

            // remove o elemento que foi selecionado
            tabelalista.remove(linha);

            // atualiza a tabela
            atualizaTabela(true);

        }

        limparCampo();


    }//GEN-LAST:event_excluirActionPerformed

    private void alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarActionPerformed
        // TODO add your handling code here:

         int nrItem = TabelaFornecedor.getSelectedRow();
        if (nrItem == -1) {
            JOptionPane.showMessageDialog(this, "Nenhum Fornecedor foi selecionada");

        } else {

            Cadastrofornecedor tela = new Cadastrofornecedor(null, true);
           Fornecedor f = tabelalista.get(nrItem);
            System.out.println(f.toString());
            tela.setFornecedor(f);
            tela.setVisible(true);
            if (tela.isSalvar()) {
               
                controledao.alterar(tela.getFornecedor());
                atualizaTabela(true);
            }

        }


    }//GEN-LAST:event_alterarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         int linha = 0;
        linha = TabelaFornecedor.getSelectedRow();
        if(linha==-1){
            JOptionPane.showMessageDialog(this,"Voce nao selecionou UM Fornecedor");
        } else {
            Fornecedor f = new Fornecedor();
            f = tabelalista.get(linha);

            Cadastrofornecedor tela = new Cadastrofornecedor(null,true);
            tela.setFornecedor(f);
            tela.desligarCampos();
            tela.setVisible(true);

        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TXTpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTpesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTpesquisarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (TXTpesquisar.getText().equals("")){
            atualizaTabela(true);
        }else{
            tabelalista.clear();
            tabelalista.addAll(controledao.listarPorNome(TXTpesquisar.getText()));
            atualizaTabela(false);
        }

        //        tabelalista.clear();
        //        tabelalista.addAll(controledao.listarPorNome(TXTpesquisar.getText()));
        //        atualizaTabela(false);
        //        TXTpesquisar.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaManutencaoFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaManutencaoFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaManutencaoFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaManutencaoFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaManutencaoFornecedor dialog = new TelaManutencaoFornecedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TXTpesquisar;
    private javax.swing.JTable TabelaFornecedor;
    private javax.swing.JButton alterar;
    private javax.swing.JButton excluir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton novo;
    // End of variables declaration//GEN-END:variables
}
