/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Visao;

import Controle.ControleCompra;
import Controle.ControleProducao;
import Modelo.Compra;
import Modelo.Fornecedor;
import Modelo.ItemCompra;
import Modelo.ItemEntrega;
import Modelo.Producao;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author APARECIDO MARCOS
 */
public class TelaManutencaoCompra extends javax.swing.JDialog {

    private Fornecedor fornecedor;

    private List<Producao> tabelalista = new ArrayList<>();
    private ControleProducao controledao = new ControleProducao();

    private List<ItemCompra> lista = new ArrayList<>();
    private ControleCompra controleCompra = new ControleCompra();
    private Compra c = new Compra();

    boolean existe;
    float calc;
    float armazena = 0;

    /**
     * Creates new form TelaManutencaoCompra
     */
    public TelaManutencaoCompra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        atualizaTabela(true);
        txtData.setText(formato.format(new Date()));
    }
    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");

    public boolean isSalvar() {
        return salvar;
    }

    public void setSalvar(boolean salvar) {
        this.salvar = salvar;
    }

    public void atualizaTabela(boolean flag) {
        DefaultTableModel modelo = (DefaultTableModel) TabelaItens.getModel();

        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }

        if (flag) {
            tabelalista.clear();
            tabelalista.addAll(controledao.listarTodos());
        }
        for (Producao d : tabelalista) {

            modelo.addRow(new Object[]{d.getIdproducao(), d.getNome(), d.getPreco()});
        }
    }

    public void atualizaTabela2(boolean a) {

        DefaultTableModel modelo = (DefaultTableModel) TabelaCompras.getModel();

        modelo.setNumRows(0);

        for (ItemCompra i : lista) {
            // float calc = i.getProduto().getValor() * i.getQuantidade();
            //TXTcoloca.setText(""+calc);
            modelo.addRow(new Object[]{i.getQuantidade(), i.getNome(), i.getPreco()
        //i.getProduto().getNome_salgado()
            });
        }

    }

    public void setItem(ItemCompra i) {

        //  i.setNome(p.getNome_salgado());
        lista.add(i);
        atualizaTabela2(true);

    }

    public void setCompra(Compra e) {

        TXTfornecedor.setText(e.getFornecedor().getNomeEmpresa());
        // txtData.setText(formato.format(e.getData()));
        //  cliente = e.getCliente();
        txtTotal.setText(String.valueOf(e.getValor()));
        lista = e.getListaCompra();
        atualizaTabela2(true);
    }

    public void desligarCampos() {
        TXTfornecedor.setEditable(false);
        TabelaCompras.setEnabled(false);
        TabelaItens.setEnabled(false);
        btSalvar.setEnabled(false);
        Passar.setEnabled(false);
        Remover.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TXTfornecedor = new javax.swing.JTextField();
        Pesquisar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btSalvar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Remover = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaCompras = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaItens = new javax.swing.JTable();
        Passar = new javax.swing.JButton();
        txtData = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("INFORMAÇÕS PARA COMPRA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Fornecedor:");

        TXTfornecedor.setEditable(false);
        TXTfornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTfornecedorActionPerformed(evt);
            }
        });

        Pesquisar.setText("Pesquisar");
        Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarActionPerformed(evt);
            }
        });

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        btSalvar.setBackground(new java.awt.Color(0, 0, 0));
        btSalvar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btSalvar.setForeground(new java.awt.Color(0, 204, 255));
        btSalvar.setText("SALVAR");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        jPanel2.add(btSalvar);

        jButton4.setBackground(new java.awt.Color(204, 51, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("CANCELAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/intercambio (1).png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setText("COMPRAS:");

        Remover.setText("Remover");
        Remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverActionPerformed(evt);
            }
        });

        TabelaCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "QUANTIDADE", "NOME", "VALOR TOTAl"
            }
        ));
        jScrollPane1.setViewportView(TabelaCompras);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel9.setText("ITENS:");

        TabelaItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "VALOR", "QUANTIDADE"
            }
        ));
        jScrollPane2.setViewportView(TabelaItens);

        Passar.setText("Passar");
        Passar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassarActionPerformed(evt);
            }
        });

        txtTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(0, 153, 51));
        txtTotal.setText("VALOR");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("TOTAL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TXTfornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Pesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(0, 10, Short.MAX_VALUE)
                                            .addComponent(Passar)
                                            .addGap(18, 18, 18))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Remover)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Pesquisar)
                        .addComponent(TXTfornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 284, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(141, 141, 141)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel8))
                    .addGap(41, 41, 41)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(Passar)
                            .addGap(18, 18, 18)
                            .addComponent(Remover)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel5))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(147, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TXTfornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTfornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTfornecedorActionPerformed

    private void PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarActionPerformed
        // TODO add your handling code here:

        PesFornecedor tela = new PesFornecedor(null, true);
        tela.setVisible(true);

        TXTfornecedor.setText(tela.getfornecedor().getNomeEmpresa());
        this.fornecedor = tela.getfornecedor();

        System.out.println(fornecedor.toString());
    }//GEN-LAST:event_PesquisarActionPerformed

    private void RemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverActionPerformed
        // TODO add your handling code here:

        int nrItem = TabelaCompras.getSelectedRow();
        if (nrItem == -1) {
            JOptionPane.showMessageDialog(this, "Nenhum produto foi selecionada");

        } else {

            int certeza = JOptionPane.showConfirmDialog(null, "Deseja remover da lista",
                    "Remover", JOptionPane.YES_OPTION, JOptionPane.CANCEL_OPTION);

            if (certeza == JOptionPane.YES_OPTION) {

                ItemCompra Item = lista.get(nrItem);

                lista.remove(nrItem);

                atualizaTabela2(true);

            }

        }
    }//GEN-LAST:event_RemoverActionPerformed

    private void PassarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassarActionPerformed
        // TODO add your handling code here:

        int nrItem = TabelaItens.getSelectedRow();
        if (nrItem == -1) {
            JOptionPane.showMessageDialog(this, "Nenhum produto foi selecionada");

        } else {

            ItemCompra i = new ItemCompra();

            String qtde;
            qtde = JOptionPane.showInputDialog("Informe a quantidade:");

            Producao p = tabelalista.get(nrItem);

            int a = p.getIdproducao();

            System.out.println("a");

            for (int j = 0; j < lista.size(); j++) {
                System.out.println("b");
                if (lista.get(j).getProducao().equals(p)) {

                    int f = JOptionPane.showConfirmDialog(this, Passar);

                    if (f == 0) {
                        lista.get(j).setQuantidade(lista.get(j).getQuantidade() + Integer.parseInt(qtde));
                        lista.get(j).setPreco(lista.get(j).getPreco() + (tabelalista.get(nrItem).getPreco() * Integer.parseInt(qtde)));
                        atualizaTabela2(false);
                        existe = true;
                    } else {
                    }

                } else {
                    existe = false;
                }

            };

            System.out.println("c");

            if (!existe) {
                i.setProducao(p);

                i.setCompra(c);

                lista.add(i);
            }

            i.setQuantidade(Integer.parseInt(qtde));
            i.setNome(p.getNome());

            calc = p.getPreco() * Float.parseFloat(qtde) + armazena;
            armazena = calc;
            txtTotal.setText(String.valueOf(armazena));

            //float preco = p.getPreco() * Float.parseFloat(qtde);
            i.setPreco(armazena);

            for (ItemCompra it : lista) {

                if (it.getCompra().equals(it.getCompra())) {

                    c.setValor(armazena);

                }

                atualizaTabela2(true);
                atualizaTabela(true);

            }

        }

    }//GEN-LAST:event_PassarActionPerformed

    private boolean salvar = false;

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // TODO add your handling code here:
        if (TXTfornecedor.getText().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Selecione O Fornecedor");
            TXTfornecedor.requestFocus();
        } else {
            Compra c = new Compra();
            c.setFornecedor(this.fornecedor);
            c.setListacompra(lista);
            c.setValor(calc);

            // c.setData( null);
            controleCompra.inserir(c);
            this.salvar = true;
            setVisible(false);
        }


    }//GEN-LAST:event_btSalvarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //dispose();
        setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaManutencaoCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaManutencaoCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaManutencaoCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaManutencaoCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaManutencaoCompra dialog = new TelaManutencaoCompra(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Passar;
    private javax.swing.JButton Pesquisar;
    private javax.swing.JButton Remover;
    private javax.swing.JTextField TXTfornecedor;
    private javax.swing.JTable TabelaCompras;
    private javax.swing.JTable TabelaItens;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel txtData;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
